### ISSUE TITLE
Error: `in_id` must be a positive integer vector

### ISSUE THREAD

**Issue by ericpgreen** [tidymodels/stacks#47]
I'm not sure if this is a feature request or a request for help, but I'm getting an error with `blend_predictions()`, and I wonder if it is possible to make this message more informative. Maybe it's plenty informative but I don't have a good grasp of stacks. 

(I posted a [separate stacks issue to RStudio Community](https://community.rstudio.com/t/stacks-model-doesnt-make-use-of-the-same-resampling-object-as-the-existing-candidates/86264?u=ericpgreen) with reprex that is more squarely in the "help please" camp)

> Error: `in_id` must be a positive integer vector.

My data stack tibble has the following:

```
# A data stack with 8 model definitions and 646 candidate members:
#   fpv_res_multinom_glmnet: 55 sub-models
#   fpv_res_rf: 125 sub-models
#   fpv_res_knn: 25 sub-models
#   fpv_res_bt: 125 sub-models
#   fpv_res_klr: 25 sub-models
#   fpv_res_mars: 152 sub-models
#   fpv_res_nb: 25 sub-models
#   fpv_res_bag: 114 sub-models
# Outcome: fpVisit (factor)
```

What is `in_id`, and what are some reasons why it would not be a positive integer vector? I can see it in the output of `str(myStack)`, but I'm not sure what to make of it.

**Comment by simonpcouch** [comment]
Thank you for giving `stacks` a try and for the issue! I had overlooked the fact that iterative tuning would change how that `folds` object was represented in the `tune::tune_*` results.

I believe this should now be fixed on `main`! Let me know if you're still seeing that `in_id` issue.. I don't use `in_id` as a variable any `stacks` source, but have some thoughts on where that could come up if you're still running into this.

Again, thanks for stress testing as we get `stacks` ready for CRAN.

**Comment by ericpgreen** [comment]
Thanks, @simonpcouch. I appreciate the quick fix! It solved the issue I posted to RStudio Community.

I'm still getting the `in_id` error for my actual use case, however. I'm not sure where `id_in` is coming from. All of the tune results I'm trying to stack have the columns: `[1] "splits"       "id"           ".metrics"     ".notes"       ".predictions"`. The mlp model has an additional column called `".iter"`.

I've narrowed it down to one model by creating a data stack with just one result at a time and then tried `blend_predictions()` until I got the error

```
baguette::bag_tree(mode = "classification",
                   cost_complexity = tune(),
                   tree_depth = tune(),
                   min_n = 2) %>%
    set_engine("rpart")
```

I inspected the data stack object related to this model with `str()` and located each instance of `in_id`, `out_id`, and `id`. These are nested pretty deep in the tibble, and I'm not sure where they come from (I don't pass any columns called `id` when I fit the original models). 

All of the instances of `in_id` are `in_id : int [1:2944] 1 2 3 4 5 6 7 8 9 10` EXCEPT one that has a length of 2943. Does this give you any ideas?

**Comment by simonpcouch** [comment]
Thanks so much for the context, @ericpgreen! Could you supply a minimal reprex including the rest of the code accompanying that `parsnip` model spec? I'm not seeing any errors with the `workflow`s and `rset` objects I just dropped it in with.

**Comment by ericpgreen** [comment]
Thanks, @simonpcouch. That makes sense. I used the `synthpop` package to create a synthetic dataset ([here](https://www.dropbox.com/s/pbug7cmj7b1clsr/df.RData?dl=1), 214KB `.RData` file). I reduced the folds to 2 to make this faster to run. I also reduced `levels` in `grid_regular()` from 5 to 1.

```
  library(tidymodels)
  library(tidyverse)
  library(stacks)

  load("df.RData")

# class of interest is last, "Yes"
  options(yardstick.event_first = FALSE)

# split data
  split <- df %>%
    initial_split(prop = 0.8, strata = class) 
  
  training <- training(split)
  testing  <- testing(split)
  
  training_cv <- vfold_cv(training, v = 2, repeats = 1, strata = class)

# recipe
  recipe <- training(split) %>%
    recipe(class ~.) %>%
    step_corr(all_numeric(), -all_outcomes()) %>%
    step_center(all_numeric(), -all_outcomes()) %>%
    step_scale(all_numeric(), -all_outcomes()) %>%
    step_dummy(all_nominal(), -all_outcomes(), one_hot = TRUE) %>%
    step_zv(all_predictors()) %>%
    themis::step_upsample(class, over_ratio = tune())
  
# stacks
  ctrl_grid <- control_stack_grid()
  ctrl_res <- control_stack_resamples()  
  
# model 
  mod_bag <- 
    baguette::bag_tree(mode = "classification",
                       cost_complexity = tune(),
                       tree_depth = tune(),
                       min_n = 2) %>%
    set_engine("rpart")
  
# workflow
  wf_bag <- 
    workflow() %>% 
    add_model(mod_bag) %>% 
    add_recipe(recipe)
  
# parameters
  par_bag <- dials::parameters(wf_bag)
  
# tune grid
  grid_bag <-
    grid_regular(par_bag, levels=1)
  
# train and tune model
  res_bag <- 
    wf_bag %>% 
    tune_grid(training_cv,
              grid = grid_bag,
              control = ctrl_grid,
              metrics = metric_set(roc_auc, accuracy, precision, f_meas))
  
# stacks
  stack_data <- stacks() %>%
    add_candidates(res_bag)
  
# fit the stack
  stack_model <- stack_data %>%
    blend_predictions() %>%
    fit_members()
```

**Comment by simonpcouch** [comment]
Much appreciated!

Your code, as is, only generates one candidate (I see [this error](https://github.com/tidymodels/stacks/blob/328e11764c7ead8b2710a5b495397137059cc1d2/R/blend_predictions.R#L295-L296) when I run your code), so I changed the tuning grid to increase the number of candidates. 

Here's what I'm seeing (some adjustments made to integrate into a reprex):

``` r
library(tidymodels)
#> ── Attaching packages ────────────────────────────────────── tidymodels 0.1.1 ──
#> ✓ broom     0.7.2           ✓ recipes   0.1.13.9000
#> ✓ dials     0.0.9.9000      ✓ rsample   0.0.8.9000 
#> ✓ dplyr     1.0.2           ✓ tibble    3.0.4.9000 
#> ✓ ggplot2   3.3.2           ✓ tidyr     1.1.2      
#> ✓ infer     0.5.3.9000      ✓ tune      0.1.1.9001 
#> ✓ modeldata 0.1.0           ✓ workflows 0.2.1.9000 
#> ✓ parsnip   0.1.3.9000      ✓ yardstick 0.0.7      
#> ✓ purrr     0.3.4
#> ── Conflicts ───────────────────────────────────────── tidymodels_conflicts() ──
#> x purrr::discard() masks scales::discard()
#> x dplyr::filter()  masks stats::filter()
#> x dplyr::lag()     masks stats::lag()
#> x recipes::step()  masks stats::step()
library(tidyverse)
library(stacks)

load(url("https://www.dropbox.com/s/pbug7cmj7b1clsr/df.RData?dl=1"))

# class of interest is last, "Yes"
options(yardstick.event_first = FALSE)

# split data
split <- df %>%
  initial_split(prop = 0.8, strata = class) 

training <- training(split)
testing  <- testing(split)

training_cv <- vfold_cv(training, v = 2, repeats = 1, strata = class)

# recipe
recipe <- training(split) %>%
  recipe(class ~.) %>%
  step_corr(all_numeric(), -all_outcomes()) %>%
  step_center(all_numeric(), -all_outcomes()) %>%
  step_scale(all_numeric(), -all_outcomes()) %>%
  step_dummy(all_nominal(), -all_outcomes(), one_hot = TRUE) %>%
  step_zv(all_predictors()) %>%
  themis::step_upsample(class, over_ratio = tune())

# model 
mod_bag <- 
  baguette::bag_tree(mode = "classification",
                     cost_complexity = tune(),
                     tree_depth = tune(),
                     min_n = 2) %>%
  set_engine("rpart")

# workflow
wf_bag <- 
  workflow() %>% 
  add_model(mod_bag) %>% 
  add_recipe(recipe)

# parameters
par_bag <- dials::parameters(wf_bag)

# train and tune model
res_bag <- 
  wf_bag %>% 
  tune_grid(training_cv,
            grid = 4,
            control = control_stack_grid(),
            metrics = metric_set(roc_auc, accuracy, precision, f_meas))
#> The workflow being saved contains a recipe, which is 0.22 Mb in memory. If this was not intentional, please set the control setting `save_workflow = FALSE`.

# data stack
stack_data <- stacks() %>%
  add_candidates(res_bag)

# model stack
stack_model <- stack_data %>%
  blend_predictions() %>%
  fit_members()

stack_model
#> ── A stacked ensemble model ─────────────────────────────────────
#> 
#> Out of 4 possible candidate members, the ensemble retained 3.
#> Lasso penalty: 1e-05.
#> 
#> The 3 highest weighted member classes are:
#> # A tibble: 3 x 3
#>   member                type     weight
#>   <chr>                 <chr>     <dbl>
#> 1 .pred_Yes_res_bag_4_1 bag_tree  1.69 
#> 2 .pred_Yes_res_bag_3_1 bag_tree  1.07 
#> 3 .pred_Yes_res_bag_2_1 bag_tree  0.297
```

<sup>Created on 2020-10-30 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

Do you mind to run this code yourself in `reprex::reprex()` and paste the results here, along with your session info, if you're still seeing that error?

**Comment by ericpgreen** [comment]
Thanks, @simonpcouch. I appreciate your efforts here. I ran your code up to `stacks()` in `reprex::reprex()` because I was getting an error there.

``` r
library(tidymodels)
#> ── Attaching packages ────────────────────────────────────── tidymodels 0.1.1 ──
#> ✓ broom     0.7.1.9000     ✓ recipes   0.1.14    
#> ✓ dials     0.0.9.9000     ✓ rsample   0.0.8.9000
#> ✓ dplyr     1.0.2          ✓ tibble    3.0.4     
#> ✓ ggplot2   3.3.2          ✓ tidyr     1.1.2     
#> ✓ infer     0.5.3          ✓ tune      0.1.1.9001
#> ✓ modeldata 0.1.0          ✓ workflows 0.2.1.9000
#> ✓ parsnip   0.1.4.9000     ✓ yardstick 0.0.7     
#> ✓ purrr     0.3.4
#> ── Conflicts ───────────────────────────────────────── tidymodels_conflicts() ──
#> x purrr::discard() masks scales::discard()
#> x dplyr::filter()  masks stats::filter()
#> x dplyr::lag()     masks stats::lag()
#> x recipes::step()  masks stats::step()
               library(tidyverse)
               library(stacks)
               
               load(url("https://www.dropbox.com/s/pbug7cmj7b1clsr/df.RData?dl=1"))
               
               # class of interest is last, "Yes"
               options(yardstick.event_first = FALSE)
               
               # split data
               split <- df %>%
                   initial_split(prop = 0.8, strata = class) 
               
               training <- training(split)
               testing  <- testing(split)
               
               training_cv <- vfold_cv(training, v = 2, repeats = 1, strata = class)
               
               # recipe
               recipe <- training(split) %>%
                   recipe(class ~.) %>%
                   step_corr(all_numeric(), -all_outcomes()) %>%
                   step_center(all_numeric(), -all_outcomes()) %>%
                   step_scale(all_numeric(), -all_outcomes()) %>%
                   step_dummy(all_nominal(), -all_outcomes(), one_hot = TRUE) %>%
                   step_zv(all_predictors()) %>%
                   themis::step_upsample(class, over_ratio = tune())
#> Registered S3 methods overwritten by 'themis':
#>   method               from   
#>   bake.step_downsample recipes
#>   bake.step_upsample   recipes
#>   prep.step_downsample recipes
#>   prep.step_upsample   recipes
#>   tidy.step_downsample recipes
#>   tidy.step_upsample   recipes
               
               # model 
               mod_bag <- 
                   baguette::bag_tree(mode = "classification",
                                      cost_complexity = tune(),
                                      tree_depth = tune(),
                                      min_n = 2) %>%
                   set_engine("rpart")
               
               # workflow
               wf_bag <- 
                   workflow() %>% 
                   add_model(mod_bag) %>% 
                   add_recipe(recipe)
               
               # parameters
               par_bag <- dials::parameters(wf_bag)
               
               # train and tune model
               res_bag <- 
                   wf_bag %>% 
                   tune_grid(training_cv,
                             grid = 4,
                             control = control_stack_grid(),
                             metrics = metric_set(roc_auc, accuracy, precision, f_meas))
#> 
#> Attaching package: 'rlang'
#> The following objects are masked from 'package:purrr':
#> 
#>     %@%, as_function, flatten, flatten_chr, flatten_dbl, flatten_int,
#>     flatten_lgl, flatten_raw, invoke, list_along, modify, prepend,
#>     splice
#> 
#> Attaching package: 'vctrs'
#> The following object is masked from 'package:tibble':
#> 
#>     data_frame
#> The following object is masked from 'package:dplyr':
#> 
#>     data_frame
#> 
#> Attaching package: 'rpart'
#> The following object is masked from 'package:dials':
#> 
#>     prune
#> 
#> Attaching package: 'themis'
#> The following objects are masked from 'package:recipes':
#> 
#>     step_downsample, step_upsample, tunable.step_downsample,
#>     tunable.step_upsample
#> The workflow being saved contains a recipe, which is 0.22 Mb in memory. If this was not intentional, please set the control setting `save_workflow = FALSE`.
               
               
               
               
               # data stack
               stack_data <- stacks() %>%
                   add_candidates(res_bag)
#> Error: Element `attr(data_stack, "train")` needs to inherit from `tbl_df`, but its class is `data.frame`.
```

<sup>Created on 2020-11-02 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>


```
> sessionInfo()
R version 4.0.2 (2020-06-22)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04.5 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/openblas/libblas.so.3
LAPACK: /usr/lib/x86_64-linux-gnu/libopenblasp-r0.2.20.so

locale:
 [1] LC_CTYPE=C.UTF-8       LC_NUMERIC=C           LC_TIME=C.UTF-8       
 [4] LC_COLLATE=C.UTF-8     LC_MONETARY=C.UTF-8    LC_MESSAGES=C.UTF-8   
 [7] LC_PAPER=C.UTF-8       LC_NAME=C              LC_ADDRESS=C          
[10] LC_TELEPHONE=C         LC_MEASUREMENT=C.UTF-8 LC_IDENTIFICATION=C   

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] themis_0.1.2.9000    rpart_4.1-15         baguette_0.0.1.9000 
 [4] vctrs_0.3.4          rlang_0.4.8          yardstick_0.0.7     
 [7] workflows_0.2.1.9000 tune_0.1.1.9001      rsample_0.0.8.9000  
[10] recipes_0.1.14       parsnip_0.1.4.9000   modeldata_0.1.0     
[13] infer_0.5.3          dials_0.0.9.9000     scales_1.1.1        
[16] broom_0.7.1.9000     tidymodels_0.1.1     stacks_0.0.0.9000   
[19] forcats_0.5.0        stringr_1.4.0        dplyr_1.0.2         
[22] purrr_0.3.4          readr_1.3.1          tidyr_1.1.2         
[25] tibble_3.0.4         ggplot2_3.3.2        tidyverse_1.3.0     

loaded via a namespace (and not attached):
  [1] clipr_0.7.1          utf8_1.1.4           tidyselect_1.1.0    
  [4] htmlwidgets_1.5.1    grid_4.0.2           pROC_1.16.2         
  [7] munsell_0.5.0        codetools_0.2-16     DT_0.15             
 [10] future_1.19.1        miniUI_0.1.1.1       withr_2.3.0         
 [13] Brobdingnag_1.2-6    colorspace_1.4-1     knitr_1.30          
 [16] rstudioapi_0.11      stats4_4.0.2         brms_2.14.0         
 [19] bayesplot_1.7.2      listenv_0.8.0        rstan_2.21.2        
 [22] TeachingDemos_2.12   DiceDesign_1.8-1     bridgesampling_1.0-0
 [25] mlr_2.18.0           coda_0.19-3          generics_0.0.2      
 [28] ipred_0.9-9          xfun_0.18            doParallel_1.0.16   
 [31] R6_2.5.0             markdown_1.1         lhs_1.1.1           
 [34] assertthat_0.2.1     promises_1.1.1       nnet_7.3-14         
 [37] gtable_0.3.0         Cubist_0.2.3         globals_0.13.1      
 [40] processx_3.4.4       timeDate_3043.102    BBmisc_1.11         
 [43] splines_4.0.2        butcher_0.1.2        earth_5.3.0         
 [46] checkmate_2.0.0      inline_0.3.15        yaml_2.2.1          
 [49] reshape2_1.4.4       abind_1.4-5          modelr_0.1.8        
 [52] threejs_0.3.3        crosstalk_1.1.0.1    backports_1.1.10    
 [55] httpuv_1.5.4         rsconnect_0.8.16     inum_1.0-1          
 [58] tools_4.0.2          lava_1.6.8           usethis_1.6.3       
 [61] ellipsis_0.3.1       ggridges_0.5.2       Rcpp_1.0.5          
 [64] plyr_1.8.6           base64enc_0.1-3      parallelMap_1.5.0   
 [67] ps_1.4.0             prettyunits_1.1.1    ParamHelpers_1.14   
 [70] zoo_1.8-8            haven_2.3.1          fs_1.5.0            
 [73] furrr_0.2.1          unbalanced_2.0       magrittr_1.5        
 [76] data.table_1.13.0    colourpicker_1.0     reprex_0.3.0        
 [79] RANN_2.6.1           GPfit_1.0-8          mvtnorm_1.1-1       
 [82] whisker_0.4          ROSE_0.0-3           matrixStats_0.56.0  
 [85] hms_0.5.3            patchwork_1.0.1      shinyjs_1.1         
 [88] mime_0.9             evaluate_0.14        xtable_1.8-4        
 [91] shinystan_2.5.0      readxl_1.3.1         gridExtra_2.3       
 [94] rstantools_2.1.1     compiler_4.0.2       V8_3.2.0            
 [97] crayon_1.3.4         StanHeaders_2.21.0-5 htmltools_0.5.0     
[100] later_1.1.0.1        Formula_1.2-4        libcoin_1.0-6       
[103] RcppParallel_5.0.2   lubridate_1.7.9      DBI_1.1.0           
[106] dbplyr_1.4.4         MASS_7.3-51.6        Matrix_1.2-18       
[109] cli_2.1.0            C50_0.1.3.1          parallel_4.0.2      
[112] gower_0.2.2          igraph_1.2.5         pkgconfig_2.0.3     
[115] xml2_1.3.2           foreach_1.5.1        dygraphs_1.1.1.6    
[118] hardhat_0.1.4        plotmo_3.6.0         prodlim_2019.11.13  
[121] rvest_0.3.6          callr_3.5.1          digest_0.6.27       
[124] rmarkdown_2.4        cellranger_1.1.0     fastmatch_1.1-0     
[127] curl_4.3             shiny_1.5.0          gtools_3.8.2        
[130] lifecycle_0.2.0      nlme_3.1-147         jsonlite_1.7.1      
[133] fansi_0.4.1          pillar_1.4.6         lattice_0.20-41     
[136] loo_2.3.1            fastmap_1.0.1        httr_1.4.2          
[139] plotrix_3.7-8        pkgbuild_1.1.0       survival_3.1-12     
[142] glue_1.4.2           xts_0.12-0           FNN_1.1.3           
[145] shinythemes_1.1.2    iterators_1.0.13     class_7.3-17        
[148] stringi_1.5.3        blob_1.2.1           partykit_1.2-10 
```

**Comment by simonpcouch** [comment]
Hmm.. I believe this was fixed in #46. Have you updated to the most recent version of `stacks`?

**Comment by ericpgreen** [comment]
Geez, you folks work fast. That error goes away with the update. Thanks. I'm not getting the id error, so I'll go back to my actual use case and see if I'm still seeing it and report back or close.

**Comment by ericpgreen** [comment]
OK, finally re-ran all models in my actual use case, created the stack, and tried to `blend_predictions()` and got the same error:

`Error: `in_id` must be a positive integer vector.`

I'm not quite sure how to create a reprex here given that my synthetic data attempt did not actually reproduce the problem. Any generic ideas about what types of things can cause this error?

**Comment by simonpcouch** [comment]
If you're not able to supply the data you're working with, I'd try to take a look at any splits you've made with `rsample`--the error you're seeing is from [here](https://github.com/tidymodels/rsample/blob/master/R/rsplit.R#L5-L6).

Another possible direction.. what do you see if you run the following code? (Replicating [this step](https://github.com/tidymodels/stacks/blob/bd7b66e36e07154f3fb1061e240c81a1ea4ee000/R/blend_predictions.R#L180).)

```
tibble::as_tibble(data_stack) %>% na.omit() %>% rsample::bootstraps()
```

This is the only spot in the `blend_predictions()` source that explicitly calls from the `rsample` namespace. 

You might also try printing the `blend_predictions()` source by running `blend_predictions` and running line-by-line. I think `check_inherits()` is the only unexported function inside of its source, which you can just skip over!

**Comment by ericpgreen** [comment]
Thanks for the leads, @simonpcouch. I'm still thinking about how to share this more directly. In the meantime, here's what I learned.

I get the same error when I run: 

```
tibble::as_tibble(data_stack) %>% na.omit() %>% rsample::bootstraps()
```

But backing up to just `tibble::as_tibble(data_stack) %>% na.omit()`, I see that the tibble has no rows. This happens because there are some NAs in the stack columns associated with the model I think is the problem.

Sooo....the presence of NAs in the data stack of the last model seems to be the culprit. I tried refitting this model with `tune_grid(levels=4` rather than passing the result of `grid_regular()` with 5 levels.

This gets me past the error to a stacked ensemble model, not yet fit:

```
── A stacked ensemble model ─────────────────────────────────────

Out of 564 possible candidate members, the ensemble retained 19.
Lasso penalty: 0.01.

The 10 highest weighted member classes are:
# A tibble: 10 x 3
   member                       type         weight
   <chr>                        <chr>         <dbl>
 1 .pred_Yes_fpv_res_nnetIter12 mlp           1.76 
 2 .pred_Yes_fpv_res_nnet_1_1   mlp           1.56 
 3 .pred_Yes_fpv_res_klr_5_5    logistic_reg  1.18 
 4 .pred_Yes_fpv_res_mars_4_24  mars          1.05 
 5 .pred_Yes_fpv_res_bt_3_11    boost_tree    0.429
 6 .pred_Yes_fpv_res_nnet_5_1   mlp           0.391
 7 .pred_Yes_fpv_res_bt_1_04    boost_tree    0.137
 8 .pred_Yes_fpv_res_mars_4_27  mars          0.119
 9 .pred_Yes_fpv_res_mars_3_23  mars          0.111
10 .pred_Yes_fpv_res_bt_1_19    boost_tree    0.108

Members have not yet been fitted with `fit_members()`.
```

My takeaway is that something went awry with a particular model that resulted in some NAs in rows of its candidates. These NAs caused the resulting tibble from `tibble::as_tibble(data_stack) %>% na.omit()` to have 0 rows, throwing the id error. 

I think this closes out my issue. Agree? Thanks for your help in digging through the code.

**Comment by simonpcouch** [comment]
Ah, great. Thanks for troubleshooting with me!

That error should be more informative. Closing in a bit. :-)
